# Generated by Django 3.1.2 on 2020-10-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='time_duration',
        ),
    ]
